PORTNAME=	batin
DISTVERSIONPREFIX=	v
DISTVERSION=	0.2.0
CATEGORIES=	security

MAINTAINER=	devahmedwalid@proton.me
COMMENT=	Security-hardened file type detection with entropy analysis
WWW=		https://github.com/ahmeddwalid/batin

LICENSE=	GPLv3
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		cargo
USE_GITHUB=	yes
GH_ACCOUNT=	ahmeddwalid

PLIST_FILES=	bin/batin

.include <bsd.port.mk>
